# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d864a6c6ad7e03523dd3d8ca47f5db33e6b03a7849ef89048cccf6f43e2c6fa96fca450994322d135661e71a1ed3feb25938cc1b4d379a7d5aa877bde8d48c7c

test:
  secret_key_base: a3276b6c1165544c70b4326ec58057a9f101f33e195e37d16a57cc6e2645d549b06df8afb548768f94732caf20156b41ab0585260eb8f16334f1f5f18c4affb9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
